### ISSUE TITLE
Use std::functions instead of function pointers to make it more C++ style

### ISSUE THREAD

**Issue by cloud-rocket** [technosoftware-gmbh/opcdaaehda-client-solution-cpp#1]
Hi, 

Are you open to consider pull requests making the code more C++ instead of C? (I'd like to submit such improvement)

(i.e. replacing pointer to functions with `std::function` lambda style callbacks)

Thanks!

**Comment by technosoftware** [comment]
Hi

Yes, this is possible now. 

You can fork the repository and commit your changes there. Once happy with your changes you can generate a 'pull request'.

You must agree to the contributor license agreement before we can accept your changes. The CLA and "I AGREE" button is automatically displayed when you perform the pull request. You can preview CLA [here](https://cla-assistant.io/technosoftware-gmbh/opcdaaehda-client-solution-cpp).

Best regards
